### ISSUE TITLE
Add Mockito to test all methods

### ISSUE THREAD

**Issue by martijnjanssen** [bartdejonge1996/goto-fail#20]
@bartdejonge1996 Needs mockito to test two remaining methods. He has not done this yet, these two methods also need to be tested.

Mockito can be added to the `pom.xml` using the following code: 

```
<dependency>
    <groupId>org.mockito</groupId>
    <artifactId>mockito-core</artifactId>
    <version>1.9.5</version>
</dependency>
```

**Comment by bart-de-jonge** [comment]
Noted, will do this in the near future
