### ISSUE TITLE
Create a logger

### ISSUE THREAD

**Issue by martijnjanssen** [bartdejonge1996/goto-fail#30]
We need a logger to keep track of all the thing in the code and see where the code fails. This will greatly help us in the future.

**Comment by martijnjanssen** [comment]
We could use log4j to implement logging. Saves is a lot of time and is properly implemented better than we can implement it.

http://logging.apache.org/log4j/2.x/

**Comment by bart-de-jonge** [comment]
Didn't you finish this in #45 @martijn9612 ?

**Comment by martijnjanssen** [comment]
This issue is not completed yet, I will be looking at a different implementation using Lombok. I think the Lombok way is going to be the better way.
