### ISSUE TITLE
Class that handles creating and loading a ScriptingProject

### ISSUE THREAD

**Issue by martijnjanssen** [bartdejonge1996/goto-fail#39]
We need to have a class that handles all the variables and settings that can potentially be loaded from the savefile. If such a savefile or some values are not present, this class should return the default settings  in the methods.

**Comment by bart-de-jonge** [comment]
This is done in the read/write methods withing ScriptingProject and bij making a new ScriptingProject using the constructor. I don't think we need a seperate class for this.
