### ISSUE TITLE
Optional<ShotBlock> in return of activeShotBlock

### ISSUE THREAD

**Issue by martijnjanssen** [bartdejonge1996/goto-fail#57]
The return type of `getActiveShotBlock` in `ControllerManager` should be changed to `Optional<ShotBlock>`. This removes unnecessary `nullPointerExceptions` in current and future code.

An optional is created via this method:

``` java
SoundCard soundcard = new Soundcard();
Optional<Soundcard> sc = Optional.of(soundcard);
```

**Comment by bart-de-jonge** [comment]
@geenen124 is this still in the planning?
