### ISSUE TITLE
Fix the scrolling cameratimelines in the directortimeline

### ISSUE THREAD

**Issue by martijnjanssen** [bartdejonge1996/goto-fail#67]
When you scroll the CameraTimelines horizontally, you can see the timeline scroll behind the DirectorTimeline.
![image](https://cloud.githubusercontent.com/assets/9624753/15107106/feacd860-15cd-11e6-9642-38a82f3de87b.png)

**Comment by martijnjanssen** [comment]
@Ezlo123 I believe you are currently working on this?

**Comment by Markvanderuit** [comment]
I'll fix this tomorrow, that's when I get around to reworking the timeline layout.

**Comment by Markvanderuit** [comment]
This is now fixed.
