### ISSUE TITLE
Drag a shot to start at count 0 not possible

### ISSUE THREAD

**Issue by martijnjanssen** [bartdejonge1996/goto-fail#77]
When you drag a shot to have it start at count 0, the shot resets since it thinks that this position is not possible for some reason.

This should also fix the bug when you try to change the endCount on a shot that starts on count 0. In this case the shot is currently resetting to the previous position, as if the shot is invalidly placed. This is not the case.

**Comment by mennoo1996** [comment]
This issue has been resolved in #93 and #101
