### ISSUE TITLE
Save and load project does not combine

### ISSUE THREAD

**Issue by martijnjanssen** [bartdejonge1996/goto-fail#79]
When I save a project it is saved, but when I go to the folder with the load option the saved project does not show up in the list.

**Comment by mennoo1996** [comment]
Works absolutely fine on my PC

**Comment by bart-de-jonge** [comment]
@martijn9612  can you reproduce this bug?

**Comment by martijn9612** [comment]
I suppose that this is a thing that linux does, so we will not fix this. We have made a way to work around this by implementing a filter for all files in #87 .

**Comment by martijnjanssen** [comment]
I suppose that this is a thing that linux does, so we will not fix this. We have made a way to work around this by implementing a filter for all files in #87 .
