### ISSUE TITLE
Extensions not auto-appended on save

### ISSUE THREAD

**Issue by bart-de-jonge** [bartdejonge1996/goto-fail#85]
When saving a project the extension is not auto-appended to the file name (on linux)

**Comment by mennoo1996** [comment]
FYI: on Windows it works fine

**Comment by bart-de-jonge** [comment]
I know, and on mac OS X as well. But the extension is added to the filename, if you remove it, the file is still stored without extension. So we should check the filename and append the extension if not present. That would mean it works on linux as well (linux does not auto-append the extension for some reason)

**Comment by martijnjanssen** [comment]
This issue can not be solved easily, I believe this is an issue of Linux itself. The smartest thing to do is to add an ExtensionFilter that shows all files for when a project is saved without an extension.
