### ISSUE TITLE
Show 2 shots next to eachother on collision

### ISSUE THREAD

**Issue by martijnjanssen** [bartdejonge1996/goto-fail#98]
When 2 shots collide, one is over the other. To make it easier to read and drag both shots, they should appear next to eachother.

**Comment by Markvanderuit** [comment]
This is going to be very hard, but yes, I had this idea as well. I'll take it up with bart after the meeting tomorrow. See what we can do.

Either that or we make sure the smaller shot is always on top, so selection works better. Could be a compromise?

**Comment by bart-de-jonge** [comment]
Is this still in the planning @Ezlo123 ?

**Comment by Markvanderuit** [comment]
To be honest, we could probably just drop this. It would be far more effort than it'd be worth.

Anyone disagree? Because otherwise I'll just close it.

**Comment by mennoo1996** [comment]
Agree
